/* tslint:disable */
/* eslint-disable */
/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CancellationEntireTripCancellationRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CancellationApi - axios parameter creator
 * @export
 */
export const CancellationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * The Cancel route should be used in the event the entire trip/booking (sale & purchase) require cancellation. In this case, the traveler/cardholder would be due a refund from the sale and the Virtual Card would be terminated to prevent the travel supplier from authorizing the Virtual Card.
         * @summary Cancel
         * @param {CancellationEntireTripCancellationRequest} [cancellationEntireTripCancellationRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        entireTripCancellation: async (cancellationEntireTripCancellationRequest?: CancellationEntireTripCancellationRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/cancel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sec0 required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: cancellationEntireTripCancellationRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/v1/cancel',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(cancellationEntireTripCancellationRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CancellationApi - functional programming interface
 * @export
 */
export const CancellationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CancellationApiAxiosParamCreator(configuration)
    return {
        /**
         * The Cancel route should be used in the event the entire trip/booking (sale & purchase) require cancellation. In this case, the traveler/cardholder would be due a refund from the sale and the Virtual Card would be terminated to prevent the travel supplier from authorizing the Virtual Card.
         * @summary Cancel
         * @param {CancellationApiEntireTripCancellationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async entireTripCancellation(requestParameters: CancellationApiEntireTripCancellationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const cancellationEntireTripCancellationRequest: CancellationEntireTripCancellationRequest = {
                DeviceGuid: requestParameters.DeviceGuid,
                SaleGuid: requestParameters.SaleGuid,
                SequenceNumber: requestParameters.SequenceNumber,
                VoidReason: requestParameters.VoidReason
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.entireTripCancellation(cancellationEntireTripCancellationRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CancellationApi - factory interface
 * @export
 */
export const CancellationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CancellationApiFp(configuration)
    return {
        /**
         * The Cancel route should be used in the event the entire trip/booking (sale & purchase) require cancellation. In this case, the traveler/cardholder would be due a refund from the sale and the Virtual Card would be terminated to prevent the travel supplier from authorizing the Virtual Card.
         * @summary Cancel
         * @param {CancellationApiEntireTripCancellationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        entireTripCancellation(requestParameters: CancellationApiEntireTripCancellationRequest, options?: AxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.entireTripCancellation(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for entireTripCancellation operation in CancellationApi.
 * @export
 * @interface CancellationApiEntireTripCancellationRequest
 */
export type CancellationApiEntireTripCancellationRequest = {
    
} & CancellationEntireTripCancellationRequest

/**
 * CancellationApiGenerated - object-oriented interface
 * @export
 * @class CancellationApiGenerated
 * @extends {BaseAPI}
 */
export class CancellationApiGenerated extends BaseAPI {
    /**
     * The Cancel route should be used in the event the entire trip/booking (sale & purchase) require cancellation. In this case, the traveler/cardholder would be due a refund from the sale and the Virtual Card would be terminated to prevent the travel supplier from authorizing the Virtual Card.
     * @summary Cancel
     * @param {CancellationApiEntireTripCancellationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CancellationApiGenerated
     */
    public entireTripCancellation(requestParameters: CancellationApiEntireTripCancellationRequest, options?: AxiosRequestConfig) {
        return CancellationApiFp(this.configuration).entireTripCancellation(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
