/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AchCreateCreditPaymentResponse
 */
export interface AchCreateCreditPaymentResponse {
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'merchantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'incomingTransactionCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'paymentId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AchCreateCreditPaymentResponse
     */
    'isCredit'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AchCreateCreditPaymentResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'payeeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'paymentStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'scheduleDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof AchCreateCreditPaymentResponse
     */
    'receiptDate'?: string;
    /**
     * 
     * @type {any}
     * @memberof AchCreateCreditPaymentResponse
     */
    'processingDate'?: any;
}

