/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Flight Data
 * @export
 * @interface AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
 */
export interface AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData {
    /**
     * Name of airline; likely carrier code
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'Airline'?: string;
    /**
     * Departure airport code
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'DepartureAirport'?: string;
    /**
     * Departure date of flight. Format: mm/dd/yyyy
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'DepartureDate'?: string;
    /**
     * Destination airport code
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'DestinationAirport'?: string;
    /**
     * Time in hours to flight departure
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'HoursToDeparture'?: string;
    /**
     * Type of journey i.e. Day/Night journey
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'JourneyType'?: string;
    /**
     * The route type i.e. Direct/Indirect
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'Route'?: string;
    /**
     * Complete flight route by country
     * @type {string}
     * @memberof AuthenticationAcquireClientAuthorizationRequestRiskDataFlightData
     */
    'RouteByCountry'?: string;
}

