/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model3DSCardholderChallengeResponseExample1 } from './model3-dscardholder-challenge-response-example1';
import { Model3DSCardholderChallengeResponseExample1Card } from './model3-dscardholder-challenge-response-example1-card';
import { Model3DSDeviceFingerprintResponseExample1 } from './model3-dsdevice-fingerprint-response-example1';

/**
 * @type AuthenticationAcquireClientAuthorization202Response
 * @export
 */
export type AuthenticationAcquireClientAuthorization202Response = Model3DSCardholderChallengeResponseExample1 | Model3DSDeviceFingerprintResponseExample1;


