/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthenticationObtain3DSecureAuthenticationResponseCard } from './authentication-obtain3-dsecure-authentication-response-card';

/**
 * 
 * @export
 * @interface AuthenticationObtain3DSecureAuthenticationResponse
 */
export interface AuthenticationObtain3DSecureAuthenticationResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'threeDSStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'SecureData'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'Cavv'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'Version'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'DirectoryServerTransactionID'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'AcsTransactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'ECI'?: string;
    /**
     * 
     * @type {AuthenticationObtain3DSecureAuthenticationResponseCard}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'card'?: AuthenticationObtain3DSecureAuthenticationResponseCard;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'exemptThreeDSRequest'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationObtain3DSecureAuthenticationResponse
     */
    'exemptThreeDSPayment'?: boolean;
}

