/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CancelPaymentsDto
 */
export interface CancelPaymentsDto {
    /**
     * Application-level value that indicates a Payout is being requested for client\'s account. Value provided by ConnexPay.
     * @type {string}
     * @memberof CancelPaymentsDto
     */
    'merchantGuid': string;
    /**
     * The Payment Guid returned in the Create Payout response.
     * @type {Array<string>}
     * @memberof CancelPaymentsDto
     */
    'payments': Array<string>;
}

