/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardCancelVirtualCardResponseCard } from './card-cancel-virtual-card-response-card';
import { CardCancelVirtualCardResponseCardHolder } from './card-cancel-virtual-card-response-card-holder';

/**
 * 
 * @export
 * @interface CardCancelVirtualCardResponse
 */
export interface CardCancelVirtualCardResponse {
    /**
     * 
     * @type {CardCancelVirtualCardResponseCardHolder}
     * @memberof CardCancelVirtualCardResponse
     */
    'cardHolder'?: CardCancelVirtualCardResponseCardHolder;
    /**
     * 
     * @type {CardCancelVirtualCardResponseCard}
     * @memberof CardCancelVirtualCardResponse
     */
    'card'?: CardCancelVirtualCardResponseCard;
}

