/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardSearchIssuedVirtualCardsRequest
 */
export interface CardSearchIssuedVirtualCardsRequest {
    /**
     * Your assigned Merchant GUID.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'MerchantGuid': string;
    /**
     * Sale GUID linked to the card you are searching.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'SaleGuid'?: string;
    /**
     * Incoming Transaction Code linked to the card you are searching.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'IncomingTransactionCode'?: string;
    /**
     * Order Number linked to the card you are searching.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'OrderNumber'?: string;
    /**
     * Order Number linked to the card you are searching.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'CustomerID'?: string;
    /**
     * Starting Issued Date linked to the card(s) you are searching.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'TimeStampFrom'?: string;
    /**
     * Ending Issued Date linked to the card(s) you are searching.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'TimeStampTo'?: string;
    /**
     * Start of Issued Amount range linked to the card(s) you are searching.
     * @type {number}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'IssuedAmountFrom'?: number;
    /**
     * End of Issued Amount range linked to the card(s) you are searching.
     * @type {number}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'IssuedAmountTo'?: number;
    /**
     * Outgoing Transaction Code linked to the card(s) you are searching.
     * @type {string}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'OutgoingTransactionCode'?: string;
    /**
     * Start of Settled Amount range linked to the card(s) you are searching.
     * @type {number}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'SettledAmountFrom'?: number;
    /**
     * End of Settled Amount range linked to the card(s) you are searching.
     * @type {number}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'SettledAmountTo'?: number;
    /**
     * Start of Settled Returned Amount range linked to the card(s) you are searching.
     * @type {number}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'ReturnedAmountFrom'?: number;
    /**
     * End of Settled Returned Amount range linked to the card(s) you are searching.
     * @type {number}
     * @memberof CardSearchIssuedVirtualCardsRequest
     */
    'ReturnedAmountTo'?: number;
}

