/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * URL Links (email) or a text document (fax) to virtual cards can be emailed/faxed by including the VCC Transmission object in the IssueLodgedCard API call. Including the transmission object for email also allows you to pull back a URL you can use within your application to direct a user to a visual representation of the virtual card.
 * @export
 * @interface CardCreateLodgedCardRequestTransmission
 */
export interface CardCreateLodgedCardRequestTransmission {
    /**
     * Methods of Transmission. Supported methods: Email, Link, Fax. Populate this parameter as \'Email\' if you want to email the virtual card to a customer or supplier. Use the \'Link\' option to have a URL included in the response.  Use the \"Fax\" option to fax the virtual card to a customer or supplier.
     * @type {Array<string>}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'TransmissionMethods'?: Array<string>;
    /**
     * Mandatory for email transmission. The email address of the intended recipient. 255 char max.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'EmailRecipient'?: string;
    /**
     * This is the phone number that should display on the virtual card and is the number that should be used if the link has expired. Up to 15 characters. Numbers and plus sign (+) allowed only.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'MerchantPhoneNumber'?: string;
    /**
     * Mandatory for email transmission. This will be the email address that populates the ‘reply to’ section of the email message. 255 char max.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'EmailFrom'?: string;
    /**
     * Mandatory for email or fax transmission. A descriptive name of the email or fax recipient. 255 char max
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'RecipientName'?: string;
    /**
     * Mandatory for email or fax transmission. High-level subject line description of the transmission contents. 255 char max.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'Subject'?: string;
    /**
     * Mandatory for email or fax transmission. The message body of the email or fax. 1024 char max.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'Message'?: string;
    /**
     * Mandatory for email transmission. The number of days after card issuance until link to VC expires. Range: 1-999 days.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'DaysToExpire'?: string;
    /**
     * Mandatory for fax transmission. This can be the client name or fax number the fax is coming from that populates the ‘FaxFrom’ section of the fax. 255 char max.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'FaxFrom'?: string;
    /**
     * Mandatory for fax transmissions.  The fax number of the intended recipient.
     * @type {string}
     * @memberof CardCreateLodgedCardRequestTransmission
     */
    'FaxRecipient'?: string;
}

