/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IssueLodgedCardResponseExample } from './issue-lodged-card-response-example';
import { IssueLodgedCardReturnCardDataFalseResponseExample } from './issue-lodged-card-return-card-data-false-response-example';
import { IssueLodgedCardReturnCardDataFalseResponseExampleCard } from './issue-lodged-card-return-card-data-false-response-example-card';
import { IssueLodgedCardReturnCardDataFalseResponseExampleCardHolder } from './issue-lodged-card-return-card-data-false-response-example-card-holder';

/**
 * @type CardCreateLodgedCardResponse
 * @export
 */
export type CardCreateLodgedCardResponse = IssueLodgedCardResponseExample | IssueLodgedCardReturnCardDataFalseResponseExample;


