/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardGetDetailResponse
 */
export interface CardGetDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'cardGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'expirationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'expiration'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'terminateDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'firstSix'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'lastFour'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'nameLine1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'nameLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof CardGetDetailResponse
     */
    'bank'?: number;
    /**
     * 
     * @type {number}
     * @memberof CardGetDetailResponse
     */
    'issuedAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'cardType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardGetDetailResponse
     */
    'purchaseType'?: string;
    /**
     * 
     * @type {number}
     * @memberof CardGetDetailResponse
     */
    'availableBalance'?: number;
}

