/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardActivateDelayedResponseCard } from './card-activate-delayed-response-card';
import { CardActivateDelayedResponseCardHolder } from './card-activate-delayed-response-card-holder';

/**
 * 
 * @export
 * @interface CardActivateDelayedResponse
 */
export interface CardActivateDelayedResponse {
    /**
     * 
     * @type {CardActivateDelayedResponseCardHolder}
     * @memberof CardActivateDelayedResponse
     */
    'cardHolder'?: CardActivateDelayedResponseCardHolder;
    /**
     * 
     * @type {CardActivateDelayedResponseCard}
     * @memberof CardActivateDelayedResponse
     */
    'card'?: CardActivateDelayedResponseCard;
}

