/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardUpdateDelayedActivationResponseCard } from './card-update-delayed-activation-response-card';
import { CardUpdateDelayedActivationResponseCardHolder } from './card-update-delayed-activation-response-card-holder';

/**
 * 
 * @export
 * @interface CardUpdateDelayedActivationResponse
 */
export interface CardUpdateDelayedActivationResponse {
    /**
     * 
     * @type {CardUpdateDelayedActivationResponseCardHolder}
     * @memberof CardUpdateDelayedActivationResponse
     */
    'cardHolder'?: CardUpdateDelayedActivationResponseCardHolder;
    /**
     * 
     * @type {CardUpdateDelayedActivationResponseCard}
     * @memberof CardUpdateDelayedActivationResponse
     */
    'card'?: CardUpdateDelayedActivationResponseCard;
}

