/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardActivateDelayedResponseCard
 */
export interface CardActivateDelayedResponseCard {
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'cardGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof CardActivateDelayedResponseCard
     */
    'amountLimit'?: number;
    /**
     * 
     * @type {number}
     * @memberof CardActivateDelayedResponseCard
     */
    'usageLimit'?: number;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'limitWindow'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'expirationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'expiration'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'firstSix'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'lastFour'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'nameLine1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'nameLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardActivateDelayedResponseCard
     */
    'cardType'?: string;
}

