/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardUpdateCardDetailsResponseCard } from './card-update-card-details-response-card';

/**
 * 
 * @export
 * @interface CardUpdateCardDetailsResponse
 */
export interface CardUpdateCardDetailsResponse {
    /**
     * 
     * @type {CardUpdateCardDetailsResponseCard}
     * @memberof CardUpdateCardDetailsResponse
     */
    'card'?: CardUpdateCardDetailsResponseCard;
    /**
     * 
     * @type {string}
     * @memberof CardUpdateCardDetailsResponse
     */
    'mccGroupName'?: string;
}

