/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardCancelVirtualCardResponseCardHolder
 */
export interface CardCancelVirtualCardResponseCardHolder {
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'cardHolderGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'address1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'address2'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof CardCancelVirtualCardResponseCardHolder
     */
    'zipcode'?: string;
}

