/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CardResendTransmissionInfoRequest
 */
export interface CardResendTransmissionInfoRequest {
    /**
     * Methods of Transmission. Supported methods: Email, Link, Fax. Populate this parameter as \'Email\' if you want to email the virtual card to a customer or supplier. Use the \'Link\' option to have a URL included in the response.  Use the \"Fax\" option to fax the virtual card to a customer or supplier.
     * @type {Array<string>}
     * @memberof CardResendTransmissionInfoRequest
     */
    'TransmissionMethods': Array<string>;
    /**
     * Mandatory when transmission is Email. Otherwise don\'t include. This is the email address of the intended recipient. 255 char max.
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'EmailRecipient'?: string;
    /**
     * This is the phone number that should display on the virtual card and is the number that should be used if the link has expired. Up to 15 characters. Numbers and plus sign (+) allowed only.
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'MerchantPhoneNumber'?: string;
    /**
     * For email transmissions, this will be the email address that populates the ‘reply to’ section of the email message. Do not include this parameter on other transmission method types. 255 char max.
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'EmailFrom'?: string;
    /**
     * A descriptive name of the email or fax recipient. Does not apply to the Link transmission method type. 255 char max
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'RecipientName'?: string;
    /**
     * High-level subject line description of the transmission contents. Does not apply to the Link transmission method type. 255 char max.
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'Subject'?: string;
    /**
     * The message body of the email or fax. Does not apply to the Link transmission method type. 1024 char max.
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'Message'?: string;
    /**
     * The number of days after card issuance until the link to the VC expires. Range: 1-999 days.
     * @type {number}
     * @memberof CardResendTransmissionInfoRequest
     */
    'DaysToExpire'?: number;
    /**
     * Mandatory for fax transmission. This can be the client name or fax number the fax is coming from that populates the ‘FaxFrom’ section of the fax. 255 char max.
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'FaxFrom'?: string;
    /**
     * Mandatory for fax transmissions.  The fax number of the intended recipient.
     * @type {string}
     * @memberof CardResendTransmissionInfoRequest
     */
    'FaxRecipient'?: string;
}

