/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DailyAccountingSummary
 */
export interface DailyAccountingSummary {
    /**
     * Merchant Guid    Unique identifier assigned to the merchant by ConnexPay.
     * @type {string}
     * @memberof DailyAccountingSummary
     */
    'merchantGuid'?: string;
    /**
     * Client Name    Unique name assigned to the client by ConnexPay.
     * @type {string}
     * @memberof DailyAccountingSummary
     */
    'clientName'?: string | null;
    /**
     * Released Date    Date on which the requested transactions were released to the client.
     * @type {string}
     * @memberof DailyAccountingSummary
     */
    'releasedDate'?: string;
    /**
     * Prior Day Cash Balance    The starting cash balance from the previous day.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'priorDayCashBalance'?: number;
    /**
     * Wire/ACH to Fund Cash Account Amount (Credit) or Withdraw from Cash Account Amount (Debit)    Funds transferred between the client\'s bank account and ConnexPay to fund transactions or to return funds to the client.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'wireAchToFundCashAmount'?: number;
    /**
     * Beginning Cash Balance    The funds the client begins the day with.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'beginningCashBalance'?: number;
    /**
     * Credit Card Sale Amount (Credit)    Total amount of incoming credit card sales added to the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'creditSaleAmount'?: number;
    /**
     * ACH Sale Amount (Credit)    Total amount of incoming ACH sales added to the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'achSaleAmount'?: number;
    /**
     * ACH Purchase Amount (Debit)    Total amount of ACH purchases decreasing the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'purchaseAchAmount'?: number;
    /**
     * Virtual Card Purchase Amount (Debit)    Total amount of issued virtual credit card purchases subtracting from the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'purchaseCardAmount'?: number;
    /**
     * Purchase Push to Card Amount    Total amount of funds paid out through PushToCard subtracting from the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'purchasePushToCardAmount'?: number;
    /**
     * Credit Card Void Amount (Debit)    Total amount of credit card sales voided subtracting from the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'creditVoidAmount'?: number;
    /**
     * Credit Card Return Amount (Debit)    Total amount of credit card sales returned subtracting from the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'creditReturnAmount'?: number;
    /**
     * Credit Chargeback Amount    Total amount of Chargebacks received on the credit card sales subtracting from the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'creditChargebackAmount'?: number;
    /**
     * Credit Adjustment Amount    Total amount of manual credit adjustments created for the client.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'creditAdjustmentAmount'?: number;
    /**
     * ACH Void Amount (Debit)    Total amount of ACH sales voided subtracting from the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'achVoidAmount'?: number;
    /**
     * ACH Return (Debit)    Total amount of ACH sales returned subtracting from the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'achReturnAmount'?: number;
    /**
     * Virtual Card Return Amount (Credit)    Total amount returned to issued virtual credit cards adding to the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'purchaseCardReturnAmount'?: number;
    /**
     * Purchase Card Chargeback Amount    Total amount of Chargebacks received on issued virtual credit cards as part of the dispute process.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'purchaseCardChargebackAmount'?: number;
    /**
     * Purchase - ACH Return Amount (Credit)    Total amount returned to issued ACHs adding to the client\'s cash balance.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'purchaseAchReturnAmount'?: number;
    /**
     * Total Activity    The sum of all debits and credits processed on the client\'s behalf for the previous day.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'totalActivity'?: number;
    /**
     * New Cash Balance    Reflects the day\'s beginning cash balance plus or minus the client\'s total activity.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'newCashBalance'?: number;
    /**
     * Credit/Debit    The amount to be credited to or debited from the client\'s bank account. ConnexPay will collaborate with  the client to determine the percentage that will be returned to the client\'s bank account each day.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'netDebitCreditToClient'?: number;
    /**
     * Ending Cash Balance    The client\'s New Cash Balance plus or minus the Credit/Debit amount.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'endingCashBalance'?: number;
    /**
     * Minimum Cash Balance (MCB)    Minimum funding balance that should be maintained by the client with ConnexPay.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'minimumCashBalance'?: number;
    /**
     * ACH Debit Reject Amount (Credit)    Total amount of payments that did not clear the supplier\'s account. Payments can be rejected for a variety of reasons, including closed accounts, incorrect account numbers, etc.
     * @type {number}
     * @memberof DailyAccountingSummary
     */
    'achDebitRejectAmount'?: number;
}

