/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DailyAccountingDetail
 */
export interface DailyAccountingDetail {
    /**
     * Description    The type of transaction being released in this detail record.    Possible Values:    ACH Debit Reject    Bank A ACH Credit Reject    Credit to Client (Withdrawal from Cash Account)    Daily Flex Funding    Debit from Client (Deposit to Cash Account)    Empty    Prior Day Cash Balance    Purchase - ACH Purchase    Purchase - ACH Return    Purchase - Push To Card Payout    Purchase - Virtual Card Chargeback    Purchase - Virtual Card Purchase    Purchase - Virtual Card Return    Reserve Balance    Sale - ACH Return    Sale - ACH Sale    Sale - ACH Void    Sale - Credit Card Adjustment    Sale - Credit Card Chargeback    Sale - Credit Card Return    Sale - Credit Card Sale    Sale - Credit Card Void    Unspecified
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'description'?: string | null;
    /**
     * Merchant Guid    Unique identifier assigned to the merchant by ConnexPay.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'merchantGuid'?: string;
    /**
     * Client Name    Unique name assigned to the client by ConnexPay.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'clientName'?: string | null;
    /**
     * Released Date    Date on which the Accounting File for this detail record was released to the client.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'releasedDate'?: string;
    /**
     * Order Number    Identifier that may be provided by the client during the Create Sale or IssueLite process to identify the order.  Can be comprised of multiple sales and purchases.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'orderNumber'?: string | null;
    /**
     * Name    The name line 1 and 2 of the virtual credit card.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'name'?: string | null;
    /**
     * Card Last Four    The last four digits of the card number associated with the detail record.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'cardLastFour'?: string | null;
    /**
     * Incoming Transaction Code (ITC)    A unique ConnexPay generated token that connects an incoming sale transaction to an outbound  purchase (virtual card or ACH) transaction. An ITC is generated and returned for each successful  authorization associated with a Sale request and is required for each purchase request.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'incomingTransactionCode'?: string | null;
    /**
     * Customer ID    Identifier that may be provided by the client during the Create Sale or IssueLite process. Can be comprised   of multiple sales and purchases. Acts as a secondary identifier in conjunction with OrderNumber.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'customerId'?: string | null;
    /**
     * Amount    Amount of the sale or purchase transaction.
     * @type {number}
     * @memberof DailyAccountingDetail
     */
    'amount'?: number;
    /**
     * Merchant Name    Name of the supplier processing the virtual credit card transaction.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'merchantName'?: string | null;
    /**
     * Ticket Number    Addendum data associated with the transaction that is returned if provided during the virtual credit card or ACH creation
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'ticketNumber'?: string | null;
    /**
     * Entity Guid    Entity Guid of the detail record to link them back to the original entity.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'entityGuid'?: string | null;
    /**
     * Purchase Type    Description of the client\'s category group. Essentially, the industry where the virtual card will be utilized.    See the Issue Card method in the Purchases API documentation for more details.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'purchaseType'?: string | null;
    /**
     * Entity Id    Entity Guid of the detail record to link them back to the original entity.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'entityId'?: string | null;
    /**
     * Issued Amount    Amount of the virtual credit card issued to the client.
     * @type {number}
     * @memberof DailyAccountingDetail
     */
    'issuedAmount'?: number;
    /**
     * Label Name    Comma-separated list of labels associated with the sale.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'labelName'?: string | null;
    /**
     * Association ID    Used to associate a virtual card to one or more sales.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'associationId'?: string | null;
    /**
     * Sale Guid    Guid value returned from the Create Sale method in the Sales API. Associated with   sale transaction detail records.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'saleGuid'?: string | null;
    /**
     * Card Guid    Guid value return from the Issue Card method in the Purchases API. Associated with   purchase and return detail records.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'cardGuid'?: string | null;
    /**
     * Date Time    For Sale detail records, the date of the sale transaction.    For Purchase and Return detail records, the date of the purchase or return settlement.    Note: This date may not be the same as ReleasedDate because release does not occur on weekends and bank holidays.
     * @type {string}
     * @memberof DailyAccountingDetail
     */
    'dateTime'?: string | null;
}

