/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DailyAccountingDetail } from './daily-accounting-detail';

/**
 * 
 * @export
 * @interface DailyAccountingDetailPaginatedItems
 */
export interface DailyAccountingDetailPaginatedItems {
    /**
     * Count of all items available in the day\'s accounting detail.
     * @type {number}
     * @memberof DailyAccountingDetailPaginatedItems
     */
    'totalItemCount'?: number;
    /**
     * Count of pages available in the day\'s accounting detail.
     * @type {number}
     * @memberof DailyAccountingDetailPaginatedItems
     */
    'pageCount'?: number;
    /**
     * Count of items in the current page.
     * @type {number}
     * @memberof DailyAccountingDetailPaginatedItems
     */
    'pageItemCount'?: number;
    /**
     * Sequence number of the current page.
     * @type {number}
     * @memberof DailyAccountingDetailPaginatedItems
     */
    'pageNumber'?: number;
    /**
     * Collection of accounting detail items for the current page.
     * @type {Array<DailyAccountingDetail>}
     * @memberof DailyAccountingDetailPaginatedItems
     */
    'items'?: Array<DailyAccountingDetail> | null;
}

