/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DtoPayments
 */
export interface DtoPayments {
    /**
     * 
     * @type {string}
     * @memberof DtoPayments
     */
    'paymentGuid'?: string;
    /**
     * Identifier needed by ConnexPay support teams to research Payment issues.
     * @type {string}
     * @memberof DtoPayments
     */
    'paymentReferenceToken'?: string;
    /**
     * Payee identifier needed by ConnexPay support teams to research Payee issues.
     * @type {string}
     * @memberof DtoPayments
     */
    'payeeReferenceToken'?: string;
    /**
     * For Payment Widget customers only. Identifier needed by ConnexPay support teams to research issues related to the Payment Widget.
     * @type {string}
     * @memberof DtoPayments
     */
    'ridReferenceToken'?: string;
    /**
     * Payment-level description highlighting the reason for this Payment.
     * @type {string}
     * @memberof DtoPayments
     */
    'memo'?: string;
    /**
     * Amount of the Payment.
     * @type {number}
     * @memberof DtoPayments
     */
    'value'?: number;
    /**
     * Status of the Payment.
     * @type {string}
     * @memberof DtoPayments
     */
    'status'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof DtoPayments
     */
    'field2'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof DtoPayments
     */
    'field3'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof DtoPayments
     */
    'field4'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof DtoPayments
     */
    'field5'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoPayments
     */
    'terminationDate'?: string;
    /**
     * The Payee\'s name.
     * @type {string}
     * @memberof DtoPayments
     */
    'payeeName'?: string;
    /**
     * Email address the Payment was sent to for the Payee.
     * @type {string}
     * @memberof DtoPayments
     */
    'email'?: string;
    /**
     * Last four digits of the Payee\'s card number.
     * @type {string}
     * @memberof DtoPayments
     */
    'lastFour'?: string;
    /**
     * Postal address line 1 of the Payee. Alphanumerics and [,.-\'] are allowed.
     * @type {string}
     * @memberof DtoPayments
     */
    'address1'?: string;
    /**
     * Postal address line 2 of the Payee. Alphanumerics and [,.-\'] are allowed.
     * @type {string}
     * @memberof DtoPayments
     */
    'address2'?: string;
    /**
     * Postal address city of the Payee.
     * @type {string}
     * @memberof DtoPayments
     */
    'city'?: string;
    /**
     * Postal address state for the Payee.
     * @type {string}
     * @memberof DtoPayments
     */
    'state'?: string;
    /**
     * Postal code for the Payee.
     * @type {string}
     * @memberof DtoPayments
     */
    'zipCode'?: string;
    /**
     * Postal address country for the Payee.
     * @type {string}
     * @memberof DtoPayments
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoPayments
     */
    'createdBy'?: string;
}

