/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DtoPayments } from './dto-payments';

/**
 * 
 * @export
 * @interface DtoPayout
 */
export interface DtoPayout {
    /**
     * Unique identifier assigned to the Payout.
     * @type {string}
     * @memberof DtoPayout
     */
    'payoutGuid'?: string;
    /**
     * The Payout identifier that will be needed by our support teams to research issues.
     * @type {string}
     * @memberof DtoPayout
     */
    'payoutReferenceToken'?: string;
    /**
     * A brief description highlighting the reason for this Payout.
     * @type {string}
     * @memberof DtoPayout
     */
    'memo'?: string;
    /**
     * The most common number used throughout the ConnexPay Portal. Transaction ID within client environment associated with the order. The value is searchable and reportable in the ConnexPay portal. This value may be sent in multiple instances of the integration for multiple purposes. The maximum length is 50 alpha-numeric characters and allows dashes ( - ).
     * @type {string}
     * @memberof DtoPayout
     */
    'orderNumber'?: string;
    /**
     * Association ID is used to tie a Payout to a sale or sales. For example, if you have several sales and one Payout to a Payee, association ID can be added to the sales and the Payout for downstream reporting.
     * @type {string}
     * @memberof DtoPayout
     */
    'associationId'?: string;
    /**
     * Transaction ID within the client environment associated with the customer. This value acts as a secondary identifier in conjunction with OrderNumber. The value is searchable and reportable in the ConnexPay portal. This value may be sent in multiple times within the integration for multiple purposes. The maximum length is 100 characters and is alpha-numeric.
     * @type {string}
     * @memberof DtoPayout
     */
    'customerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoPayout
     */
    'createdDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoPayout
     */
    'createdBy'?: string;
    /**
     * Label IDs are used to associate a Payout to specific labels within ConnexPay Bridge UI for an organization. If a Payout is tied to an incorrect Label, it will not filter or display correctly in Bridge\'s Search Grid. Please contact your Customer Care Consultant for a list of valid Label IDs before use.
     * @type {Array<number>}
     * @memberof DtoPayout
     */
    'labelIds'?: Array<number>;
    /**
     * 
     * @type {Array<DtoPayments>}
     * @memberof DtoPayout
     */
    'payments'?: Array<DtoPayments>;
}

