/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FundingMerchantCashBalance500Response
 */
export interface FundingMerchantCashBalance500Response {
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalance500Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalance500Response
     */
    'exceptionMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalance500Response
     */
    'exceptionType'?: string;
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalance500Response
     */
    'stackTrace'?: string;
}

