/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FundingMerchantCashBalanceResponseBankAccountCustomer
 */
export interface FundingMerchantCashBalanceResponseBankAccountCustomer {
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalanceResponseBankAccountCustomer
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalanceResponseBankAccountCustomer
     */
    'businessName'?: string;
}

