/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FundingMerchantCashBalance422Response
 */
export interface FundingMerchantCashBalance422Response {
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalance422Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof FundingMerchantCashBalance422Response
     */
    'errorCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalance422Response
     */
    'errorId'?: string;
}

