/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FundingMerchantCashBalanceResponseBankAccount } from './funding-merchant-cash-balance-response-bank-account';

/**
 * 
 * @export
 * @interface FundingMerchantCashBalanceResponse
 */
export interface FundingMerchantCashBalanceResponse {
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalanceResponse
     */
    'merchantGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof FundingMerchantCashBalanceResponse
     */
    'requestIp'?: string;
    /**
     * 
     * @type {number}
     * @memberof FundingMerchantCashBalanceResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FundingMerchantCashBalanceResponse
     */
    'isFundCashBalance'?: boolean;
    /**
     * 
     * @type {FundingMerchantCashBalanceResponseBankAccount}
     * @memberof FundingMerchantCashBalanceResponse
     */
    'bankAccount'?: FundingMerchantCashBalanceResponseBankAccount;
}

