/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IssueLodgedCardReturnCardDataFalseResponseExampleCard } from './issue-lodged-card-return-card-data-false-response-example-card';
import { IssueLodgedCardReturnCardDataFalseResponseExampleCardHolder } from './issue-lodged-card-return-card-data-false-response-example-card-holder';

/**
 * 
 * @export
 * @interface IssueLodgedCardReturnCardDataFalseResponseExample
 */
export interface IssueLodgedCardReturnCardDataFalseResponseExample {
    /**
     * 
     * @type {IssueLodgedCardReturnCardDataFalseResponseExampleCardHolder}
     * @memberof IssueLodgedCardReturnCardDataFalseResponseExample
     */
    'cardHolder'?: IssueLodgedCardReturnCardDataFalseResponseExampleCardHolder;
    /**
     * 
     * @type {IssueLodgedCardReturnCardDataFalseResponseExampleCard}
     * @memberof IssueLodgedCardReturnCardDataFalseResponseExample
     */
    'card'?: IssueLodgedCardReturnCardDataFalseResponseExampleCard;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardReturnCardDataFalseResponseExample
     */
    'cardBrand'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardReturnCardDataFalseResponseExample
     */
    'cardClass'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardReturnCardDataFalseResponseExample
     */
    'saleGuid'?: string;
}

