/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IssueLodgedCardResponseExampleCard
 */
export interface IssueLodgedCardResponseExampleCard {
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'cardGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'accountNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'securityCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'amountLimit'?: number;
    /**
     * 
     * @type {number}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'usageLimit'?: number;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'limitWindow'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'expirationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'expiration'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'firstSix'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'lastFour'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'nameLine1'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'nameLine2'?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'status'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'midWhitelist'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof IssueLodgedCardResponseExampleCard
     */
    'midBlacklist'?: Array<string>;
}

