/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MerchantPayeeDto
 */
export interface MerchantPayeeDto {
    /**
     * 
     * @type {number}
     * @memberof MerchantPayeeDto
     */
    'idMerchant'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MerchantPayeeDto
     */
    'isBusiness': boolean;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'dbaName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'payeeId': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'taxId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'customerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'address1'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'address2'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'preferredPayoutMethod': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'preferredCardBrand'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'preferredCardClass'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'purchaseType'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantPayeeDto
     */
    'timestamp'?: string;
}

