/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model3DSDeviceFingerprintResponseExample1Card } from './model3-dsdevice-fingerprint-response-example1-card';

/**
 * 
 * @export
 * @interface Model3DSDeviceFingerprintResponseExample1
 */
export interface Model3DSDeviceFingerprintResponseExample1 {
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'redirectUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'redirectUrlRequestPayload'?: string;
    /**
     * 
     * @type {Model3DSDeviceFingerprintResponseExample1Card}
     * @memberof Model3DSDeviceFingerprintResponseExample1
     */
    'card'?: Model3DSDeviceFingerprintResponseExample1Card;
}

