/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Model3DSCardholderChallengeResponseExample1Card
 */
export interface Model3DSCardholderChallengeResponseExample1Card {
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample1Card
     */
    'first6'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample1Card
     */
    'first4'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample1Card
     */
    'last4'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample1Card
     */
    'cardHolderName'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample1Card
     */
    'cardType'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample1Card
     */
    'expirationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample1Card
     */
    'guid'?: string;
}

