/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model3DSDeviceFingerprintResponseExampleCard } from './model3-dsdevice-fingerprint-response-example-card';

/**
 * 
 * @export
 * @interface Model3DSDeviceFingerprintResponseExample
 */
export interface Model3DSDeviceFingerprintResponseExample {
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'redirectUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'redirectUrlRequestPayload'?: string;
    /**
     * 
     * @type {Model3DSDeviceFingerprintResponseExampleCard}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'card'?: Model3DSDeviceFingerprintResponseExampleCard;
    /**
     * 
     * @type {boolean}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'exemptThreeDSRequest'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Model3DSDeviceFingerprintResponseExample
     */
    'exemptThreeDSPayment'?: boolean;
}

