/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model3DSCardholderChallengeResponseExampleCard } from './model3-dscardholder-challenge-response-example-card';

/**
 * 
 * @export
 * @interface Model3DSCardholderChallengeResponseExample
 */
export interface Model3DSCardholderChallengeResponseExample {
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'threeDSStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'directoryServerTransactionID'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'acsTransactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'redirectUrl'?: string;
    /**
     * 
     * @type {Model3DSCardholderChallengeResponseExampleCard}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'card'?: Model3DSCardholderChallengeResponseExampleCard;
    /**
     * 
     * @type {boolean}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'exemptThreeDSRequest'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Model3DSCardholderChallengeResponseExample
     */
    'exemptThreeDSPayment'?: boolean;
}

