/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentsDto
 */
export interface PaymentsDto {
    /**
     * The Payee identifier used by ConnexPay support teams to research issues related to the Payee.
     * @type {string}
     * @memberof PaymentsDto
     */
    'payeeReferenceToken'?: string;
    /**
     * For Payment Widget customers only. This is the identifier that used by ConnexPay support teams to research issues related to the Payment Widget.
     * @type {string}
     * @memberof PaymentsDto
     */
    'ridReferenceToken'?: string;
    /**
     * Unique identifier assigned to the Payee.
     * @type {string}
     * @memberof PaymentsDto
     */
    'payeeGuid': string;
    /**
     * Unique identifier assigned to the Payment.
     * @type {string}
     * @memberof PaymentsDto
     */
    'paymentGuid'?: string;
    /**
     * Unique identifier assigned when using the Payment Widget.
     * @type {string}
     * @memberof PaymentsDto
     */
    'ridGuid'?: string;
    /**
     * Amount of the Payment.
     * @type {number}
     * @memberof PaymentsDto
     */
    'value': number;
    /**
     * Payment-level description highlighting the reason for this Payment.
     * @type {string}
     * @memberof PaymentsDto
     */
    'memo'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof PaymentsDto
     */
    'field2'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof PaymentsDto
     */
    'field3'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof PaymentsDto
     */
    'field4'?: string;
    /**
     * Additional data field that can be used to provide additional data to the Payee and for your reporting purposes.
     * @type {string}
     * @memberof PaymentsDto
     */
    'field5'?: string;
}

