/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentsDto } from './payments-dto';

/**
 * 
 * @export
 * @interface PayoutDto
 */
export interface PayoutDto {
    /**
     * Guid assigned to the Payout by ConnexPay upon creation of a Payout.
     * @type {string}
     * @memberof PayoutDto
     */
    'payoutGuid'?: string;
    /**
     * Application-level value that indicates a Payout is being requested for client\'s account. Value provided by ConnexPay.
     * @type {string}
     * @memberof PayoutDto
     */
    'merchantGuid': string;
    /**
     * The Payout identifier that will be needed by ConnexPay support teams to research issues.
     * @type {string}
     * @memberof PayoutDto
     */
    'payoutReferenceToken'?: string;
    /**
     * A brief description highlighting the reason for this Payout.
     * @type {string}
     * @memberof PayoutDto
     */
    'memo': string;
    /**
     * Status of the Payout.
     * @type {string}
     * @memberof PayoutDto
     */
    'status'?: string;
    /**
     * 
     * @type {Array<PaymentsDto>}
     * @memberof PayoutDto
     */
    'payments': Array<PaymentsDto>;
    /**
     * The most common number used throughout the ConnexPay Portal. Transaction ID within client environment associated with the order. The value is searchable and reportable in the ConnexPay portal. This value may be sent in multiple instances of the integration for multiple purposes. The maximum length is 50 alpha-numeric characters and allows dashes ( - ).
     * @type {string}
     * @memberof PayoutDto
     */
    'orderNumber'?: string;
    /**
     * Transaction ID within the client environment associated with the customer. This value acts as a secondary identifier in conjunction with OrderNumber. The value is searchable and reportable in the ConnexPay portal. This value may be sent in multiple times within the integration for multiple purposes. The maximum length is 100 characters and is alpha-numeric.
     * @type {string}
     * @memberof PayoutDto
     */
    'customerId'?: string;
    /**
     * Association ID is used to tie a Payout to a sale or sales. For example, if you have several sales and one Payout to a Payee, association ID can be added to the sales and the Payout for downstream reporting.
     * @type {string}
     * @memberof PayoutDto
     */
    'associationId'?: string;
    /**
     * Label IDs are used to associate a Payout to specific labels within ConnexPay Bridge UI for an organization. If a Payout is tied to an incorrect Label, it will not filter or display correctly in Bridge\'s Search Grid. Please contact your Customer Care Consultant for a list of valid Label IDs before use.
     * @type {Array<number>}
     * @memberof PayoutDto
     */
    'labelIds'?: Array<number>;
}

