/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ReturnSearchSaleReturnsRequest
 */
export interface ReturnSearchSaleReturnsRequest {
    /**
     * Merchant’s Guid.
     * @type {string}
     * @memberof ReturnSearchSaleReturnsRequest
     */
    'MerchantGuid'?: string;
    /**
     * Amount of the transaction. Min. amt.: $0.50
     * @type {number}
     * @memberof ReturnSearchSaleReturnsRequest
     */
    'AmountFrom'?: number;
    /**
     * Amount of the transaction. Min. amt.: $0.50
     * @type {number}
     * @memberof ReturnSearchSaleReturnsRequest
     */
    'AmountTo'?: number;
    /**
     * Cardholder’s name. Providing information in this field allows a user of the ConnexPay portal to search for a transaction using the cardholder name.
     * @type {string}
     * @memberof ReturnSearchSaleReturnsRequest
     */
    'CardHolderName'?: string;
    /**
     * Return’s status.  Allowed values:  1. Transaction - Approved 2. Transaction - Declined 3. Transaction - Created - Local 4. Transaction - Created - Error: Processor not reached 5. Transaction - Processor Error 6. Transaction - Approved - Warning
     * @type {string}
     * @memberof ReturnSearchSaleReturnsRequest
     */
    'Status'?: string;
    /**
     * Return’s TimeStamp.
     * @type {string}
     * @memberof ReturnSearchSaleReturnsRequest
     */
    'TimeStampFrom'?: string;
    /**
     * Return’s TimeStamp.
     * @type {string}
     * @memberof ReturnSearchSaleReturnsRequest
     */
    'TimeStampTo'?: string;
}

