/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReturnSearchSaleReturnsResponseSearchResultDTOInner } from './return-search-sale-returns-response-search-result-dtoinner';

/**
 * 
 * @export
 * @interface ReturnSearchSaleReturnsResponse
 */
export interface ReturnSearchSaleReturnsResponse {
    /**
     * 
     * @type {number}
     * @memberof ReturnSearchSaleReturnsResponse
     */
    'pageCurrent'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReturnSearchSaleReturnsResponse
     */
    'pageCurrentResults'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReturnSearchSaleReturnsResponse
     */
    'pageTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReturnSearchSaleReturnsResponse
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof ReturnSearchSaleReturnsResponse
     */
    'totalResults'?: number;
    /**
     * 
     * @type {any}
     * @memberof ReturnSearchSaleReturnsResponse
     */
    'cardSummary'?: any;
    /**
     * 
     * @type {Array<ReturnSearchSaleReturnsResponseSearchResultDTOInner>}
     * @memberof ReturnSearchSaleReturnsResponse
     */
    'searchResultDTO'?: Array<ReturnSearchSaleReturnsResponseSearchResultDTOInner>;
}

