/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReturnItemRequestResponseSaleCardCustomer } from './return-item-request-response-sale-card-customer';

/**
 * 
 * @export
 * @interface ReturnItemRequestResponseSaleCard
 */
export interface ReturnItemRequestResponseSaleCard {
    /**
     * 
     * @type {string}
     * @memberof ReturnItemRequestResponseSaleCard
     */
    'first4'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnItemRequestResponseSaleCard
     */
    'last4'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnItemRequestResponseSaleCard
     */
    'cardNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnItemRequestResponseSaleCard
     */
    'cardHolderName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnItemRequestResponseSaleCard
     */
    'expirationDate'?: string;
    /**
     * 
     * @type {ReturnItemRequestResponseSaleCardCustomer}
     * @memberof ReturnItemRequestResponseSaleCard
     */
    'customer'?: ReturnItemRequestResponseSaleCardCustomer;
}

