/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Enhanced Level 2 and Level 3 card data is a set of additional information for business, commercial, corporate, purchasing, and government cardholders.
 * @export
 * @interface SaleCreateTransactionRequestEnhancedData
 */
export interface SaleCreateTransactionRequestEnhancedData {
    /**
     * Sales Tax amount
     * @type {string}
     * @memberof SaleCreateTransactionRequestEnhancedData
     */
    'SaleTax'?: string;
}

