/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SaleCreateTransactionRequestRiskDataFlightPassengersInner
 */
export interface SaleCreateTransactionRequestRiskDataFlightPassengersInner {
    /**
     * Country of origin of passenger
     * @type {string}
     * @memberof SaleCreateTransactionRequestRiskDataFlightPassengersInner
     */
    'Country'?: string;
    /**
     * DOB of first passenger
     * @type {string}
     * @memberof SaleCreateTransactionRequestRiskDataFlightPassengersInner
     */
    'DateOfBirth'?: string;
    /**
     * Passport, drivers license or id# associated with passenger
     * @type {string}
     * @memberof SaleCreateTransactionRequestRiskDataFlightPassengersInner
     */
    'Id'?: string;
    /**
     * Passenger information. Each passenger should be sent in it\'s own object.
     * @type {string}
     * @memberof SaleCreateTransactionRequestRiskDataFlightPassengersInner
     */
    'Name'?: string;
}

