/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SaleCreateTransactionRequestBankAccountCustomer
 */
export interface SaleCreateTransactionRequestBankAccountCustomer {
    /**
     * Mandatory for ACH Sales.  Min Length = 2 Max Length = 30
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'FirstName'?: string;
    /**
     * Mandatory for ACH Sales. Min Length = 2 Max Length = 30
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'LastName'?: string;
    /**
     * Customer\'s phone number. Phone number up to 15 characters. Numbers and plus sign (+) allowed only.
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'Phone'?: string;
    /**
     * Customer\'s City
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'City'?: string;
    /**
     * Customer\'s short name state.  The ISO 3166-2 CA and US state or province code of a customer. Length = 2.
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'State'?: string;
    /**
     * Customer\'s country. The ISO country code of a customer’s country.  Length = 2
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'Country'?: string;
    /**
     * Customer\'s valid email address which is available in various reports. It is critical that SendReceipt is set to FALSE so that ConnexPay does not send a receipt to the cardholder when the transaction is processed
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'Email'?: string;
    /**
     * Customer billing address 1. It is strongly recommended to send this value in a card-not-present environment such that enhanced Address Validation (AVS) can be performed on transaction and the lowest possible interchange is received on transaction. Note: only the street number value portion of address is used for enhanced AVS check
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'Address1'?: string;
    /**
     * Customer billing address 2. It is strongly recommended to send this value in a card-not-present environment such that Address Validation (AVS) can be performed on transaction and the lowest possible interchange is received on transaction
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'Address2'?: string;
    /**
     * Customer billing postal code. It is strongly recommended to send this value in a card-not-present environment such that basic Address Validation (AVS) can be performed on transaction and the lowest possible interchange is received on transaction.  Only the a standard U.S. 5 digit zip code is eligible for basic AVS check. Min Length = 2 Max Length = 15. Alphanumerics and \"-\" allowed.
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'Zip'?: string;
    /**
     * Customer\'s date of birth. Allowed format: YYYY-MM-DD. For example: 2002-05-30
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'DateOfBirth'?: string;
    /**
     * Customer\'s driver license number.  Only letters, numbers and a hyphen is allowed
     * @type {number}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'DriversLicenseNumber'?: number;
    /**
     * Mandatory when DriverLicenseNumber is provided. Customer\'s driver license short name state. The ISO 3166-2 CA and US state or province code of a customer.  Length = 2
     * @type {string}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'DriversLicenseState'?: string;
    /**
     * Last 4 of Customer\'s Social Security Number
     * @type {number}
     * @memberof SaleCreateTransactionRequestBankAccountCustomer
     */
    'SSN4'?: number;
}

