/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SaleCreateTransactionRequestBankAccount } from './sale-create-transaction-request-bank-account';
import { SaleCreateTransactionRequestBrowserData } from './sale-create-transaction-request-browser-data';
import { SaleCreateTransactionRequestCard } from './sale-create-transaction-request-card';
import { SaleCreateTransactionRequestConnexPayTransaction } from './sale-create-transaction-request-connex-pay-transaction';
import { SaleCreateTransactionRequestCustomParametersInner } from './sale-create-transaction-request-custom-parameters-inner';
import { SaleCreateTransactionRequestCustomer } from './sale-create-transaction-request-customer';
import { SaleCreateTransactionRequestEnhancedData } from './sale-create-transaction-request-enhanced-data';
import { SaleCreateTransactionRequestRiskData } from './sale-create-transaction-request-risk-data';

/**
 * 
 * @export
 * @interface SaleCreateTransactionRequest
 */
export interface SaleCreateTransactionRequest {
    /**
     * Device\'s Guid provided by ConnexPay
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'DeviceGuid': string;
    /**
     * Amount of the transaction that will be processed. Note: this value is submitted multiple times (in different formats) within the integration to support different purposes i.e. risk analysis, merchant processing, etc.  The minimum amount is: $0.50.
     * @type {number}
     * @memberof SaleCreateTransactionRequest
     */
    'Amount': number;
    /**
     * Allowed values:  \"credit\" (default if TenderType not provided) and \"ach\"
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'TenderType'?: string;
    /**
     * Transaction sequence number within client environment. Provide a unique SequenceNumber for each new request. If a sale request with the same parameter data and the same sequence number is sent within 30 minutes it will be considered a duplicate request and the sale will not process. Note: value is not searchable or reportable in Bridge.  Alphanumeric.
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'SequenceNumber'?: string;
    /**
     * This is the most common number you\'ll see throughout the ConnexPay Portal.  Transaction ID within client environment associated with the order. The value is searchable and reportable in the ConnexPay portal. This value may be sent in multiple instances of the integration for multiple purposes. Customers in the travel space often send the Record Locator/PNR in this field.  The maximum length is 50 alpha-numeric characters and allows dashes ( - ).
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'OrderNumber'?: string;
    /**
     * Value determines whether or not a customer shall be emailed a receipt from the ConnexPay platform if the email address is provided in the API customer block. The default value is TRUE. Set to FALSE so that an email receipt is not sent to the customer. Set to TRUE or leave empty if you want e-mail to be sent. If TRUE, customer\'s email must be included in the \"Card.Customer.email\" parameter.
     * @type {boolean}
     * @memberof SaleCreateTransactionRequest
     */
    'SendReceipt'?: boolean;
    /**
     * Indicator that determines if client would like to evaluate the transactions as risk only rather than process as merchant of record and create a virtual card. The allowed values:  1. Set to TRUE will only run risk validations. If TenderType is not set to Credit, setting TRUE will throw a validation error.  2. Set to FALSE will run risk validations and an authorization on the card. For this option a Processing Merchant account is required, contact ConnexPay support if any questions.  3. Set to NULL and your Merchant Level settings would apply.
     * @type {boolean}
     * @memberof SaleCreateTransactionRequest
     */
    'RiskProcessingOnly'?: boolean;
    /**
     * US Clients only: The statement description allows a client to customize the Merchant name that appears on the cardholder statement such that the cardholder recognizes the transaction on their statement. For US Merchants: ConnexPay recommends sending a recognizable DBA along with the PNR i.e. ABC Travel ABC123.  The maximum length is 25 alpha-numeric characters.  For EU Merchants: The maximum length of the description is 13 alphanumeric characters and the DBA Name and City will automatically be coded to appear as part of the statement description. Note: functionality not applicable for American Express program.
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'StatementDescription'?: string;
    /**
     * Transaction ID within client environment associated with the customer. This value acts as a secondary identifier in conjunction with OrderNumber. The value is searchable and reportable in the ConnexPay portal. This value may be sent in multiple times within the integration for multiple purposes.  The maximum length is 100 characters and is alpha-numeric.
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'CustomerID'?: string;
    /**
     * Set a future date on which to run this sale, at least one day from creation date and within 600 days. If this parameter is supplied a record for this sale is created, supplied consumer card information is internally tokenized, but fraud check and authorization do not occur until ConnexPay processes it on the supplied ActivationDate. Alternatively, a client can force activation via the Activate API (see below). If this date is not supplied a sale is authorized and the consumer\'s credit card is charged immediately.
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'ActivationDate'?: string;
    /**
     * Mandatory if TenderType is ACH. Customer\'s IP Address is a required parameter for all ACH Sales transactions to adhere to NACHA regulations.
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'RequestIp'?: string;
    /**
     * 
     * @type {SaleCreateTransactionRequestConnexPayTransaction}
     * @memberof SaleCreateTransactionRequest
     */
    'ConnexPayTransaction': SaleCreateTransactionRequestConnexPayTransaction;
    /**
     * 
     * @type {SaleCreateTransactionRequestRiskData}
     * @memberof SaleCreateTransactionRequest
     */
    'RiskData': SaleCreateTransactionRequestRiskData;
    /**
     * 
     * @type {SaleCreateTransactionRequestCard}
     * @memberof SaleCreateTransactionRequest
     */
    'Card'?: SaleCreateTransactionRequestCard;
    /**
     * 
     * @type {SaleCreateTransactionRequestBankAccount}
     * @memberof SaleCreateTransactionRequest
     */
    'BankAccount'?: SaleCreateTransactionRequestBankAccount;
    /**
     * 
     * @type {SaleCreateTransactionRequestCustomer}
     * @memberof SaleCreateTransactionRequest
     */
    'Customer'?: SaleCreateTransactionRequestCustomer;
    /**
     * 
     * @type {SaleCreateTransactionRequestEnhancedData}
     * @memberof SaleCreateTransactionRequest
     */
    'EnhancedData'?: SaleCreateTransactionRequestEnhancedData;
    /**
     * Utilize the Association ID field to tie a virtual card to a sale or sales. For example, if you have several sales and one virtual card payment to a supplier, you can add association ID to the sales and the virtual card for downstream reporting.
     * @type {string}
     * @memberof SaleCreateTransactionRequest
     */
    'AssociationId'?: string;
    /**
     * You can add custom parameters to your sale request in the event that you need to associate additional information with the pay-in. For example, if you want to add an invoice number you would include the custom parameters object with the name parameter = \"invoice\" and the value parameter as the invoice number. This requires customized reporting so you\'ll need to work with your implementations specialist to determine what\'s required.
     * @type {Array<SaleCreateTransactionRequestCustomParametersInner>}
     * @memberof SaleCreateTransactionRequest
     */
    'CustomParameters'?: Array<SaleCreateTransactionRequestCustomParametersInner>;
    /**
     * Utilize Label IDs to associate a sale to a specific label(s) within ConnexPay Bridge UI for your organization. If a sale is tied to an incorrect Label, it will not filter or display correctly in Bridge\'s Search Grid. Please contact your Customer Care Consultant for a list of valid Label IDs before use.
     * @type {Array<string>}
     * @memberof SaleCreateTransactionRequest
     */
    'LabelIDs'?: Array<string>;
    /**
     * 
     * @type {SaleCreateTransactionRequestBrowserData}
     * @memberof SaleCreateTransactionRequest
     */
    'BrowserData'?: SaleCreateTransactionRequestBrowserData;
}

