/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SaleSearchSalesRequest
 */
export interface SaleSearchSalesRequest {
    /**
     * Merchant’s Guid.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'MerchantGuid'?: string;
    /**
     * Amount of the transaction. Min. amt.: $0.50
     * @type {number}
     * @memberof SaleSearchSalesRequest
     */
    'AmountFrom'?: number;
    /**
     * Amount of the transaction. Min. amt.: $0.50
     * @type {number}
     * @memberof SaleSearchSalesRequest
     */
    'AmountTo'?: number;
    /**
     * Cardholder’s name.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'CardHolderName'?: string;
    /**
     * Card last four number.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'CardLastFour'?: string;
    /**
     * Card type.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'CardType'?: string;
    /**
     * Sale’s InvoiceNumber.
     * @type {number}
     * @memberof SaleSearchSalesRequest
     */
    'InvoiceNumber'?: number;
    /**
     * Sale’s order number. Length = 17.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'OrderNumber'?: string;
    /**
     * Sale’s order Date.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'OrderDateFrom'?: string;
    /**
     * Sale’s order Date.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'OrderDateTo'?: string;
    /**
     * Sale’s TimeStamp.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'TimeStampFrom'?: string;
    /**
     * Sale’s TimeStamp.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'TimeStampTo'?: string;
    /**
     * Sale’s status. Allowed values:  1. Transaction - Approved 2. Transaction - Declined 3. Transaction - Created - Local 4. Transaction - Created - Error: Processor not reached 5. Transaction - Processor Error 6. Transaction - Approved - Warning
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'Status'?: string;
    /**
     * Merchant Customer Id.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'MerchantCustomerId'?: string;
    /**
     * Delayed Activation Sales to be included or not
     * @type {boolean}
     * @memberof SaleSearchSalesRequest
     */
    'Activated'?: boolean;
    /**
     * Activation Start Date. This field is applicable only when Activated flag is set to true.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'ActivationDateFrom'?: string;
    /**
     * Activation End Date. This field is applicable only when Activated flag is set to true.
     * @type {string}
     * @memberof SaleSearchSalesRequest
     */
    'ActivationDateTo'?: string;
}

