/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SaleCreateTransaction201ResponseBankAccountCustomer } from './sale-create-transaction201-response-bank-account-customer';

/**
 * 
 * @export
 * @interface SaleCreateTransaction201ResponseBankAccount
 */
export interface SaleCreateTransaction201ResponseBankAccount {
    /**
     * 
     * @type {string}
     * @memberof SaleCreateTransaction201ResponseBankAccount
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleCreateTransaction201ResponseBankAccount
     */
    'accountType'?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleCreateTransaction201ResponseBankAccount
     */
    'accountNumberLastFour'?: string;
    /**
     * 
     * @type {string}
     * @memberof SaleCreateTransaction201ResponseBankAccount
     */
    'nameOnAccount'?: string;
    /**
     * 
     * @type {SaleCreateTransaction201ResponseBankAccountCustomer}
     * @memberof SaleCreateTransaction201ResponseBankAccount
     */
    'customer'?: SaleCreateTransaction201ResponseBankAccountCustomer;
}

