/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Model3DSCardholderChallengeResponseExample } from './model3-dscardholder-challenge-response-example';
import { Model3DSCardholderChallengeResponseExampleCard } from './model3-dscardholder-challenge-response-example-card';
import { Model3DSDeviceFingerprintResponseExample } from './model3-dsdevice-fingerprint-response-example';

/**
 * @type SaleCreateTransaction202Response
 * @export
 */
export type SaleCreateTransaction202Response = Model3DSCardholderChallengeResponseExample | Model3DSDeviceFingerprintResponseExample;


