/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SettingTokenizeBankAccountInfoResponseAccountHolderBankAccount
 */
export interface SettingTokenizeBankAccountInfoResponseAccountHolderBankAccount {
    /**
     * 
     * @type {string}
     * @memberof SettingTokenizeBankAccountInfoResponseAccountHolderBankAccount
     */
    'bankAccountGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingTokenizeBankAccountInfoResponseAccountHolderBankAccount
     */
    'accountType'?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingTokenizeBankAccountInfoResponseAccountHolderBankAccount
     */
    'accountHolderName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SettingTokenizeBankAccountInfoResponseAccountHolderBankAccount
     */
    'last4Digits'?: string;
}

