/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SettlementSearchVirtualCardSettlementsRequest
 */
export interface SettlementSearchVirtualCardSettlementsRequest {
    /**
     * Merchant\'s Guid.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'MerchantGuid': string;
    /**
     * Card\'s Issued Date.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'DateFrom'?: string;
    /**
     * Card\'s Issued Date.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'DateTo'?: string;
    /**
     * Card settlement post date.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'PostedDateFrom'?: string;
    /**
     * Card settlement post date.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'PostedDateTo'?: string;
    /**
     * Order Number. Max. Length = 50.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'OrderNumber'?: string;
    /**
     * Issued Amount of the Card.
     * @type {number}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'IssuedAmountFrom'?: number;
    /**
     * Issued Amount of the Card.
     * @type {number}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'IssuedAmountTo'?: number;
    /**
     * Card last four number.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'IssuedCardLastFour'?: string;
    /**
     * Posted Amount of the Card.
     * @type {number}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'PostedAmountFrom'?: number;
    /**
     * Posted Amount of the Card.
     * @type {number}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'PostedAmountTo'?: number;
    /**
     * Card\'s expiration date.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'ExpirationDateFrom'?: string;
    /**
     * Card\'s expiration date.
     * @type {string}
     * @memberof SettlementSearchVirtualCardSettlementsRequest
     */
    'ExpirationDateTo'?: string;
}

