/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SettingTokenizeBankAccountInfoRequestAccountHolder } from './setting-tokenize-bank-account-info-request-account-holder';

/**
 * 
 * @export
 * @interface SettingTokenizeBankAccountInfoRequest
 */
export interface SettingTokenizeBankAccountInfoRequest {
    /**
     * Merchant\'s guid. Application level value that indicates the ACH payment is being requested for clients account. Value provided by ConnexPay.
     * @type {string}
     * @memberof SettingTokenizeBankAccountInfoRequest
     */
    'MerchantGuid': string;
    /**
     * Name of supplier to whom payment will be made
     * @type {string}
     * @memberof SettingTokenizeBankAccountInfoRequest
     */
    'SupplierName': string;
    /**
     * 
     * @type {SettingTokenizeBankAccountInfoRequestAccountHolder}
     * @memberof SettingTokenizeBankAccountInfoRequest
     */
    'AccountHolder': SettingTokenizeBankAccountInfoRequestAccountHolder;
}

