/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { StatusGroup3DsAuthenticationStatusResponseCard } from './status-group3-ds-authentication-status-response-card';

/**
 * 
 * @export
 * @interface StatusGroup3DsAuthenticationStatusResponse
 */
export interface StatusGroup3DsAuthenticationStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'secureData'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'eci'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'cavv'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'directoryServerTransactionID'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'acsTransactionId'?: string;
    /**
     * 
     * @type {StatusGroup3DsAuthenticationStatusResponseCard}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'card'?: StatusGroup3DsAuthenticationStatusResponseCard;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'processorResponseCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof StatusGroup3DsAuthenticationStatusResponse
     */
    'processorMessage'?: string;
}

