/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TokenRequestHppTokenResponse
 */
export interface TokenRequestHppTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenRequestHppTokenResponse
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequestHppTokenResponse
     */
    'merchantName'?: string;
    /**
     * 
     * @type {number}
     * @memberof TokenRequestHppTokenResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TokenRequestHppTokenResponse
     */
    'resultRedirectUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequestHppTokenResponse
     */
    'tempToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequestHppTokenResponse
     */
    'expiration'?: string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequestHppTokenResponse
     */
    'logoUrl'?: string;
}

