/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TransactionCaptureAuthorizationResponseSaleConnexPayTransaction
 */
export interface TransactionCaptureAuthorizationResponseSaleConnexPayTransaction {
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleConnexPayTransaction
     */
    'guid'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionCaptureAuthorizationResponseSaleConnexPayTransaction
     */
    'expectedPayments'?: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleConnexPayTransaction
     */
    'incomingTransCode'?: string;
}

