/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionSearchVirtualCardHistoryResponseTransactionsInner } from './transaction-search-virtual-card-history-response-transactions-inner';

/**
 * 
 * @export
 * @interface TransactionSearchVirtualCardHistoryResponse
 */
export interface TransactionSearchVirtualCardHistoryResponse {
    /**
     * 
     * @type {Array<TransactionSearchVirtualCardHistoryResponseTransactionsInner>}
     * @memberof TransactionSearchVirtualCardHistoryResponse
     */
    'transactions'?: Array<TransactionSearchVirtualCardHistoryResponseTransactionsInner>;
}

