/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionCaptureAuthorizationResponseSaleCardCustomer } from './transaction-capture-authorization-response-sale-card-customer';

/**
 * 
 * @export
 * @interface TransactionCaptureAuthorizationResponseSaleCard
 */
export interface TransactionCaptureAuthorizationResponseSaleCard {
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'first6'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'first4'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'last4'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'cardHolderName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'cardType'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'expirationDate'?: string;
    /**
     * 
     * @type {TransactionCaptureAuthorizationResponseSaleCardCustomer}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'customer'?: TransactionCaptureAuthorizationResponseSaleCardCustomer;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSaleCard
     */
    'guid'?: string;
}

