/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionCaptureAuthorizationResponseSaleCard } from './transaction-capture-authorization-response-sale-card';
import { TransactionCaptureAuthorizationResponseSaleConnexPayTransaction } from './transaction-capture-authorization-response-sale-connex-pay-transaction';
import { TransactionCaptureAuthorizationResponseSaleRiskResponse } from './transaction-capture-authorization-response-sale-risk-response';

/**
 * 
 * @export
 * @interface TransactionCaptureAuthorizationResponseSale
 */
export interface TransactionCaptureAuthorizationResponseSale {
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'batchStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'amount'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'activated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'tenderType'?: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'effectiveAmount'?: number;
    /**
     * 
     * @type {TransactionCaptureAuthorizationResponseSaleRiskResponse}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'riskResponse'?: TransactionCaptureAuthorizationResponseSaleRiskResponse;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'orderNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'cardDataSource'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'customerID'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'batchGuid'?: string;
    /**
     * 
     * @type {TransactionCaptureAuthorizationResponseSaleConnexPayTransaction}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'connexPayTransaction'?: TransactionCaptureAuthorizationResponseSaleConnexPayTransaction;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'processorStatusCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'processorResponseMessage'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'wasProcessed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'authCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'refNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'customerReceipt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'statementDescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'generatedBy'?: string;
    /**
     * 
     * @type {TransactionCaptureAuthorizationResponseSaleCard}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'card'?: TransactionCaptureAuthorizationResponseSaleCard;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'addressVerificationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'addressVerificationResult'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'cvvVerificationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCaptureAuthorizationResponseSale
     */
    'cvvVerificationResult'?: string;
}

