/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Account Holder Address
 * @export
 * @interface TransactionCreateAchCreditPaymentRequestAccountHolderAddress
 */
export interface TransactionCreateAchCreditPaymentRequestAccountHolderAddress {
    /**
     * Address 1 up to 50 characters
     * @type {string}
     * @memberof TransactionCreateAchCreditPaymentRequestAccountHolderAddress
     */
    'Address1'?: string;
    /**
     * Address 2 up to 50 characters
     * @type {string}
     * @memberof TransactionCreateAchCreditPaymentRequestAccountHolderAddress
     */
    'Address2'?: string;
    /**
     * City up to 50 characters
     * @type {string}
     * @memberof TransactionCreateAchCreditPaymentRequestAccountHolderAddress
     */
    'City'?: string;
    /**
     * US State up to 2 characters
     * @type {string}
     * @memberof TransactionCreateAchCreditPaymentRequestAccountHolderAddress
     */
    'State'?: string;
    /**
     * Country. \'US\' only as of now
     * @type {string}
     * @memberof TransactionCreateAchCreditPaymentRequestAccountHolderAddress
     */
    'Country'?: string;
    /**
     * ZipCode up to 10 characters
     * @type {string}
     * @memberof TransactionCreateAchCreditPaymentRequestAccountHolderAddress
     */
    'ZipCode'?: string;
}

