/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface UpdatePayeeDto
 */
export interface UpdatePayeeDto {
    /**
     * First name for the Payee to be updated.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'firstName'?: string;
    /**
     * Last name for the Payee to be updated.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'lastName'?: string;
    /**
     * Email address for the Payee to be updated.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'email'?: string;
    /**
     * Postal address line 1 for the Payee to be updated. Alphanumerics and [,.-\'] are allowed.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'address1'?: string;
    /**
     * Postal address line 2 for the Payee to be updated. Alphanumerics and [,.-\'] are allowed.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'address2'?: string;
    /**
     * Postal address city for the Payee to be updated.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'city'?: string;
    /**
     * Postal address state for the Payee to be updated.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'state'?: string;
    /**
     * Postal code for the Payee to be updated.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'zipCode'?: string;
    /**
     * Phone number for the Payee to be updated, up to 10-character string.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'phone'?: string;
    /**
     * Status for the Payee to be updated.
     * @type {string}
     * @memberof UpdatePayeeDto
     */
    'status'?: string;
}

