/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ValidationSearchVerifyOperationResponseSearchResultDTOInner } from './validation-search-verify-operation-response-search-result-dtoinner';

/**
 * 
 * @export
 * @interface ValidationSearchVerifyOperationResponse
 */
export interface ValidationSearchVerifyOperationResponse {
    /**
     * 
     * @type {number}
     * @memberof ValidationSearchVerifyOperationResponse
     */
    'pageCurrent'?: number;
    /**
     * 
     * @type {number}
     * @memberof ValidationSearchVerifyOperationResponse
     */
    'pageCurrentResults'?: number;
    /**
     * 
     * @type {number}
     * @memberof ValidationSearchVerifyOperationResponse
     */
    'pageTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof ValidationSearchVerifyOperationResponse
     */
    'pageSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof ValidationSearchVerifyOperationResponse
     */
    'totalResults'?: number;
    /**
     * 
     * @type {any}
     * @memberof ValidationSearchVerifyOperationResponse
     */
    'cardSummary'?: any;
    /**
     * 
     * @type {Array<ValidationSearchVerifyOperationResponseSearchResultDTOInner>}
     * @memberof ValidationSearchVerifyOperationResponse
     */
    'searchResultDTO'?: Array<ValidationSearchVerifyOperationResponseSearchResultDTOInner>;
}

