/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VerifyCardResponseExampleCardCustomer
 */
export interface VerifyCardResponseExampleCardCustomer {
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'dateOfBirth'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'address1'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'address2'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'ssN4'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyCardResponseExampleCardCustomer
     */
    'driverLicenseNumber'?: string;
}

