/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SaleCreateTransactionRequestBankAccountCustomer } from './sale-create-transaction-request-bank-account-customer';

/**
 * Conditional - Mandatory if Verify Bank Account is the parameter requested.
 * @export
 * @interface VerificationCardBankAccountRequestBankAccount
 */
export interface VerificationCardBankAccountRequestBankAccount {
    /**
     * Accepted account types are: Saving or Checking
     * @type {string}
     * @memberof VerificationCardBankAccountRequestBankAccount
     */
    'AccountType': string;
    /**
     * 9 Digit routing number
     * @type {string}
     * @memberof VerificationCardBankAccountRequestBankAccount
     */
    'RoutingNumber': string;
    /**
     * Account number up to 20 characters
     * @type {string}
     * @memberof VerificationCardBankAccountRequestBankAccount
     */
    'AccountNumber': string;
    /**
     * Name on the account for ACH transfer (upto 50 characters)
     * @type {string}
     * @memberof VerificationCardBankAccountRequestBankAccount
     */
    'NameOnAccount': string;
    /**
     * Encrypted Token previously assigned to Bank Account. Either AccountAndRoutingNumberToken or both AccountNumber  and RoutingNumber  should be provided.
     * @type {string}
     * @memberof VerificationCardBankAccountRequestBankAccount
     */
    'AccountAndRoutingNumberToken'?: string;
    /**
     * 
     * @type {SaleCreateTransactionRequestBankAccountCustomer}
     * @memberof VerificationCardBankAccountRequestBankAccount
     */
    'Customer'?: SaleCreateTransactionRequestBankAccountCustomer;
}

