/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VerifyBankAccountResponseExampleBankAccount } from './verify-bank-account-response-example-bank-account';

/**
 * 
 * @export
 * @interface VerifyBankAccountResponseExample
 */
export interface VerifyBankAccountResponseExample {
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExample
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExample
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExample
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExample
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {VerifyBankAccountResponseExampleBankAccount}
     * @memberof VerifyBankAccountResponseExample
     */
    'bankAccount'?: VerifyBankAccountResponseExampleBankAccount;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExample
     */
    'processorStatusCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VerifyBankAccountResponseExample
     */
    'wasProcessed'?: boolean;
}

