/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VerifyBankAccountResponseExampleBankAccountCustomer } from './verify-bank-account-response-example-bank-account-customer';

/**
 * 
 * @export
 * @interface VerifyBankAccountResponseExampleBankAccount
 */
export interface VerifyBankAccountResponseExampleBankAccount {
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccount
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccount
     */
    'accountType'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccount
     */
    'accountNumberLastFour'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccount
     */
    'nameOnAccount'?: string;
    /**
     * 
     * @type {VerifyBankAccountResponseExampleBankAccountCustomer}
     * @memberof VerifyBankAccountResponseExampleBankAccount
     */
    'customer'?: VerifyBankAccountResponseExampleBankAccountCustomer;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccount
     */
    'accountAndRoutingNumberToken'?: string;
}

