/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VerifyBankAccountResponseExampleBankAccountCustomer
 */
export interface VerifyBankAccountResponseExampleBankAccountCustomer {
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccountCustomer
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccountCustomer
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyBankAccountResponseExampleBankAccountCustomer
     */
    'lastName'?: string;
}

