/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoidCreateVoidResponseSale } from './void-create-void-response-sale';

/**
 * 
 * @export
 * @interface VoidCreateVoidResponse
 */
export interface VoidCreateVoidResponse {
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'guid'?: string;
    /**
     * 
     * @type {number}
     * @memberof VoidCreateVoidResponse
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'batchStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'saleGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'voidReason'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'processorStatusCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoidCreateVoidResponse
     */
    'wasProcessed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'batchGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'authCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'refNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'invoiceNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'customerReceipt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponse
     */
    'sequenceNumber'?: string;
    /**
     * 
     * @type {VoidCreateVoidResponseSale}
     * @memberof VoidCreateVoidResponse
     */
    'sale'?: VoidCreateVoidResponseSale;
}

