/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VoidCreateVoidResponseSaleCard } from './void-create-void-response-sale-card';

/**
 * 
 * @export
 * @interface VoidCreateVoidResponseSale
 */
export interface VoidCreateVoidResponseSale {
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'guid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'batchStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'deviceGuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof VoidCreateVoidResponseSale
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof VoidCreateVoidResponseSale
     */
    'effectiveAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'orderNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'orderDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'batchGuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'processorStatusCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'processorResponseMessage'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof VoidCreateVoidResponseSale
     */
    'wasProcessed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'authCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'refNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'invoiceNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'customerReceipt'?: string;
    /**
     * 
     * @type {string}
     * @memberof VoidCreateVoidResponseSale
     */
    'customData'?: string;
    /**
     * 
     * @type {VoidCreateVoidResponseSaleCard}
     * @memberof VoidCreateVoidResponseSale
     */
    'card'?: VoidCreateVoidResponseSaleCard;
}

