/*
ConnexPay Reporting API

REST API for retrieving reporting data. Currently Daily Accounting data only.

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface VoidCreateVoidRequest
 */
export interface VoidCreateVoidRequest {
    /**
     * Device’s Guid provided by ConnexPay.
     * @type {string}
     * @memberof VoidCreateVoidRequest
     */
    'DeviceGuid': string;
    /**
     * Sale Transaction Guid
     * @type {string}
     * @memberof VoidCreateVoidRequest
     */
    'SaleGuid'?: string;
    /**
     * Return\'s Guid
     * @type {string}
     * @memberof VoidCreateVoidRequest
     */
    'ReturnGuid'?: string;
    /**
     * Sale Reference Number
     * @type {number}
     * @memberof VoidCreateVoidRequest
     */
    'SaleReferenceNumber'?: number;
    /**
     * Guid to include in request when voiding an Auth Only request.
     * @type {string}
     * @memberof VoidCreateVoidRequest
     */
    'AuthOnlyGuid'?: string;
    /**
     * Indicates the reason the transaction was voided.  Allowed values:  1. POST_AUTH_USER_DECLINE 2. DEVICE_TIMEOUT 3. DEVICE_UNAVAILABLE 4. PARTIAL_REVERSAL 5. TORN_TRANSACTIONS 6. POST_AUTH_CHIP_DECLINE
     * @type {string}
     * @memberof VoidCreateVoidRequest
     */
    'VoidReason'?: string;
    /**
     * Amount to be voided.  Note: Amount is be used once only for credit card Sales and should not exceed corresponding Sale’s Amount.
     * @type {number}
     * @memberof VoidCreateVoidRequest
     */
    'Amount'?: number;
    /**
     * Transaction sequence number within client environment. Provide a unique SequenceNumber for each new request. If the same value is sent within 30 minutes it will be considered a duplicate request. Note: value is not searchable or reportable in ConnexPay portal.  Alphanumeric.
     * @type {string}
     * @memberof VoidCreateVoidRequest
     */
    'SequenceNumber'?: string;
}

